import bcrypt from 'bcrypt';

const data = {
  users: [
    {
      name: 'Amir',
      email:'amir@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'TapTatti',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Nurly',
      email:'nurly@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],

    products: [
      {

        name: 'Napaleon Cake',
        category: 'Cake',
        image: '/images/p1.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Biscuit',
        rating: 5.0,
        numReviews: 20,
        description: 'Airy, crispy puff pastry made from fine flour and sour butter from the French range, sandwiched with delicious custard infused with vanilla.',
        ingredient: 'Flour, water, food salt, vinegar, butter 82.5%, powdered sugar, dough crumbs, cream, vanilla extract, sugar, boiled milk, yolk, starch.',
        pastry: 'Biscuit pastry',
      },
      {

        name: 'Milk Girl',
        category: 'Cake',
        image: '/images/p2.jpg',
        price: 100,
        countInStock: 20,
        brand: 'Biscuit',
        rating: 4.0,
        numReviews: 10,
        description: 'Amazing combination of airy cakes based on condensed milk and a delicate layer of Cream Cheese with natural whipped cream.',
        ingredient: 'Egg, condensed milk, flour, baking powder, salt, cremetto cheese, sugar, cream, white chocolate glaze, syrup, white calllebaut chocolate.',
        pastry: 'Biscuit pastry',
      },
      {

        name: 'Whoopi Pie',
        category: 'Cake',
        image: '/images/p3.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Biscuit',
        rating: 4.8,
        numReviews: 17,
        description: 'Soaked chocolate sponge cake based on Italian cocoa combined with natural whipped cream and Cream Cheese.',
        ingredient: 'flour, dark cocoa Italy, sugar, sour cream, butter 72.5%, melange, milk, baking powder, baking soda, edible salt, vanilla sugar, cremetto cheese, cream, starch syrup, milk chocolate, syrup (sugar , water).',
        pastry: 'Biscuit pastry',
      },
      {

        name: 'Red Velvet',
        category: 'Cake',
        image: '/images/p4.jpg',
        price: 78,
        countInStock: 15,
        brand: 'TapTatti',
        rating: 4.5,
        numReviews: 14,
        description: 'Round cake, consists of 3 red damp biscuit cakes, cream of curd cheese with natural cream is evenly applied between the layers of the biscuit. On the sides, the cake is sprinkled with crumbs, on top of the cake is decorated with 8 roses.',
        ingredient: 'Curd cheese, Natural cream, Flour, Sugar, Sunflower oil, Kefir, Powdered sugar, Eggs, Baking powder, Food coloring, Chocolate, Cocoa, Salt.',
        pastry: 'TapTatti pastry',
      },
      {

        name: 'Tiramisu',
        category: 'Cake',
        image: '/images/p5.jpg',
        price: 65,
        countInStock: 5,
        brand: 'TapTatti',
        rating: 4.5,
        numReviews: 10,
        description: 'Round cake, consists of 2 layers of biscuit soaked in coffee and milk syrup, cream of curd cheese with natural cream is evenly applied between the layers of biscuit. The sides of the cake are open, cocoa powder is poured on top and the inscription "Tiramisu" is applied with powdered sugar.',
        ingredient: 'Eggs, Curd cheese, Vegetable cream, Milk, Natural cream, Flour, Sugar, Powdered sugar, Cocoa, Baking powder, Coffee.',
        pastry: 'TapTatti pastry',
      },
      {
 
        name: 'Apple Pie',
        category: 'Pie',
        image: '/images/p6.jpg',
        price: 139,
        countInStock: 12,
        brand: 'TapTatti',
        rating: 4.5,
        numReviews: 15,
        description: 'Sand base, filling with apples, raisins and walnuts.',
        ingredient: 'Apple, flour, egg, sugar, milk, baking powder, butter.',
        pastry: 'TapTatti pastry',
      },
      {
        
        name: 'Mulatto cake',
        category: 'Cake',
        image: '/images/p7.jpg',
        price: 125,
        countInStock: 15,
        brand: 'Biscuit',
        rating: 5.0,
        numReviews: 20,
        description: 'In 100 grams of product, application 6.5 g - protein, 23.47 g - fat, 54.7 g - carbohydrates Shelf life: 5 days Storage conditions: In the refrigerator at a temperature from +2 to +6 ° С',
        ingredient: 'Egg, Salt, Gelatin, Water, Yogurt, Sugar, Milk, Cocoa, Wheat Flour.',
        pastry: 'Biscuit pastry',
      },
      {
        
        name: 'Peanut tartlet',
        category: 'Tartlet',
        image: '/images/p8.jpg',
        price: 130,
        countInStock: 30,
        brand: 'Biscuit',
        rating: 3.0,
        numReviews: 17,
        description: 'Sand basket based on peanut flour with delicate custard, decorated with fresh raspberries and honey crumbs..',
        ingredient: 'Dough: 72.5% sweet butter, sugar, flour, salt, peanut flour, egg..',
        pastry: 'Biscuit pastry',
      },
      {
        
        name: 'Currant cake',
        category: 'Cake',
        image: '/images/p9.jpg',
        price: 170,
        countInStock: 70,
        brand: 'Biscuit',
        rating: 2.0,
        numReviews: 5,
        description: 'In 100 grams of product, application 5 g protein, 18 g fat, 54 g carbohydrates Shelf life: 5 days Storage conditions: In the refrigerator at a temperature from +2 to +6 ° С',
        ingredient: 'Flour, Sugar, Water, Milk, Egg, Butter, Salt, Currant.',
        pastry: 'Biscuit pastry',
      },
    ],
    
  };
  export default data;